config/routes.rb
Rails.application.routes.draw do
  resources :activities
  root "pages#home"
  
  # pages 
  get 'home',     to: 'pages#home',     as: :home
  get 'about',    to: 'pages#about',    as: :about
  get 'team',     to: 'pages#team',     as: :team
  get 'contact',  to: 'pages#contact',  as: :contact
  get 'faq',      to: 'pages#faq',      as: :faq
  get 'donate',   to: 'pages#donate',   as: :donate
  get 'sponsors', to: 'pages#sponsors', as: :sponsors
  get 'terms',    to: 'pages#terms',    as: :terms
  get 'privacy',  to: 'pages#privacy',  as: :privacy
  get 'testimonials',    to: 'pages#testimonials',    as: :testimonials
  get 'metrics',  to: 'pages#metrics',  as: :metrics
  
  # ph datasets get request
  get 'update_selection', to: 'ph_datasets#update_selection', as: :update_selection
  get 'retrieve_data', to: 'ph_datasets#retrieve_data', as: :retrieve_data
  get 'ph',  to: 'ph_datasets#index',  as: :ph
  get 'pH',  to: 'ph_datasets#index',  as: :pH
  get 'portal',  to: 'ph_datasets#index',  as: :portal
  
  match 'admin/users/:id' => 'admin/users#destroy', :via => :delete, 
                      :as => :destroy_admin_user
  match 'admin/projects/:id' => 'admin/projects#destroy', :via => :delete, 
                      :as => :destroy_admin_project
                      
  resources :projects do
    resources :scientific_data
    resources :comments 
    resources :contributors, only: [:index, :create, :destroy]
    resources :field_notes
    resources :sites
  end
  
  resources :debris do 
    resources :comments 
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
    resources :profiles   
  end
  
  resources :explore, only: [:index]
  
  resources :comments do 
    resources :comments
  end
  
  namespace :admin do
    root 'application#index'
    resources :users do 
      member do
        patch :archive
      end
    end
    
    resources :projects do 
      member do
        patch :archive
      end
    end
    
    resources :states do
      member do
        get :make_default
      end
    end
    
    resources :secoora_datasets do
      collection do
        get :process_data
      end
    end
    resources :teams
    resources :body_of_waters
    resources :tags
  end
  
  resources :trackers do 
    resources :items
    resources :comments
    member do 
        get 'manage'
    end
  end
  
  resources :items, only: [] do
    resources :statuses, only: [:create]
  end
  
  resources :notifications do
    collection do 
      post :mark_as_read
    end
  end
  
  resources :tags, only: [:index, :show]
  
  resources :favorite_projects, only: [:create, :destroy]
  
  resources :ph_datasets do
    collection do
      get :update_data
      get 'clean_data', to: 'ph_datasets#clean_data', as: :clean_data
    end
  end
  
  mount ActionCable.server, at: '/cable'
end

app/models/field_note.rb
class FieldNote < ApplicationRecord
  belongs_to :project
  belongs_to :user
  
  validates :note, presence: true
  
  scope :persisted, lambda { where.not(id: nil) }
  scope :ord_recent, lambda { order('created_at DESC') }
  scope :ord_oldest, lambda { order('created_at ASC') }
end

app/controllers/field_notes_controller.rb
class FieldNotesController < ActionController::Base
  before_action :set_project
  
  def new
    @field_note = FieldNote.new
  end
  
  def create
    @field_note = @project.field_notes.build(field_note_params)
    @field_note.user_id = current_user.id
    respond_to do |format|
      if @field_note.save
        format.html { redirect_to @project, 
                      notice: "Field note was created successfully" }
        format.json { render :show, status: :created, location: @project }
        format.js
      else
        format.html { render :new, alert: "Field note was note created successfully " }
        format.json { render json: @project, status: :unprocessable_entity }
        format.js
      end
    end
  end
  
  def destroy
    @field_note = @project.field_notes.find(params[:id])
    @field_note.destroy
    respond_to do |format|
      format.html { redirect_to @project,
        notice: "Field not has been destroyed" }
      format.json { head :no_content }
      format.js
    end
  end
  
  private 
    def field_note_params
        params.require(:field_note).permit(:note)
    end
    
    def set_project
      @project = Project.friendly_id.find(params[:project_id])
    end
end

app/views/field_notes/_field_note.html.haml
.col-md-3{id: "field_note_#{field_note.id}"}
  .box.box-default.box-solid
    .box-header
      = link_to field_note.user.username, user_profiles_path(field_note.user)
    .box-body
      = field_note.try(:note)
    .box-footer
      = time_ago_in_words(field_note.try(:created_at))
      ago
      .pull-right
        - if field_note.user == current_user
          = link_to "#{fa_icon("trash")}".html_safe,
            [@project, field_note], method: :delete, remote: true,
            data: { confirm: "Are you sure you want to delete this note? "},
            class: "btn btn-danger", title: "Delete" 

app/views/field_notes/_form.html.haml
= simple_form_for [@project, @project.field_notes.new], remote: true do |f|
  .input-group
    = f.text_field :note, 
      class: "form-control",
      input_html: { id: "note_content"},
      type: "text", placeholder: "Enter a field note..."
    %span.input-group-btn
      = f.button :submit, "Submit".html_safe, 
        class: "btn btn-default btn-flat", id: "note_submit_#{@project.id}"
    

app/views/field_notes/create.js.erb
$(document).ready(function() { 
  $("#field_notes").
      prepend("<%=j render 'field_notes/field_note', field_note: @field_note %>");
  $("#field_note_note").val('');
});

app/views/field_notes/destroy.js.erb
$("#field_note_<%= @field_note.id %>").fadeOut(500, function() {
  $(this).remove();
});