config/routes.rb
Rails.application.routes.draw do
  resources :activities
  root "pages#home"
  
  # pages 
  get 'home',     to: 'pages#home',     as: :home
  get 'about',    to: 'pages#about',    as: :about
  get 'team',     to: 'pages#team',     as: :team
  get 'contact',  to: 'pages#contact',  as: :contact
  get 'faq',      to: 'pages#faq',      as: :faq
  get 'donate',   to: 'pages#donate',   as: :donate
  get 'sponsors', to: 'pages#sponsors', as: :sponsors
  get 'terms',    to: 'pages#terms',    as: :terms
  get 'privacy',  to: 'pages#privacy',  as: :privacy
  get 'testimonials',    to: 'pages#testimonials',    as: :testimonials
  get 'metrics',  to: 'pages#metrics',  as: :metrics
  
  # ph datasets get request
  get 'update_selection', to: 'ph_datasets#update_selection', as: :update_selection
  get 'retrieve_data', to: 'ph_datasets#retrieve_data', as: :retrieve_data
  get 'ph',  to: 'ph_datasets#index',  as: :ph
  get 'pH',  to: 'ph_datasets#index',  as: :pH
  get 'portal',  to: 'ph_datasets#index',  as: :portal
  
  match 'admin/users/:id' => 'admin/users#destroy', :via => :delete, 
                      :as => :destroy_admin_user
  match 'admin/projects/:id' => 'admin/projects#destroy', :via => :delete, 
                      :as => :destroy_admin_project
                      
  resources :projects do
    resources :scientific_data
    resources :comments 
    resources :contributors, only: [:index, :create, :destroy]
    resources :field_notes
    resources :sites
  end
  
  resources :debris do 
    resources :comments 
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
    resources :profiles   
  end
  
  resources :explore, only: [:index]
  
  resources :comments do 
    resources :comments
  end
  
  namespace :admin do
    root 'application#index'
    resources :users do 
      member do
        patch :archive
      end
    end
    
    resources :projects do 
      member do
        patch :archive
      end
    end
    
    resources :states do
      member do
        get :make_default
      end
    end
    
    resources :secoora_datasets do
      collection do
        get :process_data
      end
    end
    resources :teams
    resources :body_of_waters
    resources :tags
  end
  
  resources :trackers do 
    resources :items
    resources :comments
    member do 
        get 'manage'
    end
  end
  
  resources :items, only: [] do
    resources :statuses, only: [:create]
  end
  
  resources :notifications do
    collection do 
      post :mark_as_read
    end
  end
  
  resources :tags, only: [:index, :show]
  
  resources :favorite_projects, only: [:create, :destroy]
  
  resources :ph_datasets do
    collection do
      get :update_data
      get 'clean_data', to: 'ph_datasets#clean_data', as: :clean_data
    end
  end
  
  mount ActionCable.server, at: '/cable'
end

app/models/state.rb
class State < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  #Scopes
  scope :desc, lambda { order('created_at DESC')  }
  scope :asc,  lambda { order('created_at ASC')  }
  scope :excluding_unavailable, lambda { where(available: true)}
  
  # Max number of states per page 
  max_paginates_per 25
  
  def make_default!
    State.update_all(default: false)
    update!(default: true)
  end
  
  def self.default
    find_by(default: true)
  end
  
  def to_s
    name
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::ApplicationController
  before_action :set_state, only: [:edit, :update, :destroy]
  
  def index
    @states = State.all.order(:created_at).page params[:page]
  end
  
  def new
    @state = State.new
  end
  
  def create
    @state = State.new(state_params)
    
    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been created."
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @state.update(state_params)
      flash[:notice] = "State has been updated."
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been updated."
      render "edit"
    end
  end
  
  def destroy
    if @state.destroy
      flash[:notice] = "State has been deleted."
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been deleted."
    end
  end
  
  def make_default
    @state = State.find(params[:id])
    @state.make_default!
    
    flash[:notice] = "'#{@state.name}' is now the default state."
    redirect_to admin_states_path
  end
  
  
  private 
    def set_state
      @state = State.find(params[:id])
    end
    
    def state_params
      params.require(:state).permit(:name, :color, :available)
    end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.haml
= simple_form_for([:admin, state]) do |f|
  .form-group
    = f.input :name, placeholder: "Name of the state",
      input_html: { class: "form-control", id: "Name" }
  .form-group
    = f.input :color, placeholder: "HTML color code or color name",
      input_html: { class: "form-control", id: "Color" }
    (This has to be a HTML color code!)
  .form-group
    .checkbox
      = f.input :available, label: "Make available?"
  .form-group
    = f.submit class: 'btn btn-primary btn-flat'

app/views/admin/states/edit.html.haml
- title "Edit State - Admin"
.container
  %section
    .content
      %h2
        = @state.name
        %small
          Edit State
      .box
        .box-header.with-border
          .box-title
            State Details
        .box-body
          .row
            .col-md-6
              = render "form", state: @state

app/views/admin/states/index.html.haml
-title("States - Admin")
.container
  %section.content
    .title-block
      .row
        .col-md-12
          %h2.title
            States
            %small
              A list of all states available to users
    .box
      .box-header
        .box-title
          = page_entries_info @states, entry_name: 'state'
        .box-tools.pull-right
          = link_to fa_icon("plus") + " New State", new_admin_state_path, 
              class: "btn btn-sm rounded-s btn-box-tool"
      .box-body
        .row
          .col-md-6
            %table.table.table-striped
              %tr
                %th
                  State Name
                %th
                  Default
                %th 
                  Available?
                %th
                  Actions
              - @states.desc.each do |state|
                %tr
                  %td
                    = render "states/state", state: state
                  %td
                    - if state.default?
                      (Default)
                    - else
                      = link_to "Make Default", 
                        make_default_admin_state_path(state)
                  %td
                    = state.available?
                  %td
                    = link_to "#{fa_icon("edit")} Edit".html_safe, 
                      [:edit, :admin, state], type: "button",  
                      class: "btn btn-default btn-xs"
                    = link_to "#{fa_icon("trash")} Delete".html_safe, 
                      [:admin, state], 
                      title: 'Delete', class: "btn btn-default btn-xs", 
                      method: :delete,
                      data: { confirm: "Are you sure you want to delete this State?"} 

app/views/admin/states/new.html.haml
- title "New State - Admin"
.container
  %section
    .content
      %h2
        State
        %small
          Add A New State
      .box
        .box-header.with-border
          .box-title
            State Details
        .box-body
          .row
            .col-md-6
              = render "form", state: @state